spring:
  application:
    name: generic-rest-api
  datasource:
    url: jdbc:postgresql://gra:5432/generic
    driver-class-name: org.postgresql.Driver
    username: generic
    password: generic
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db-changelog.yaml